definitions:
  models.GetQueriesResponse:
    properties:
      count:
        type: integer
      queries:
        items:
          $ref: '#/definitions/models.Query'
        type: array
    type: object
  models.Query:
    properties:
      calls:
        type: integer
      max_exec_time:
        type: number
      mean_exec_time:
        type: number
      min_exec_time:
        type: number
      query:
        type: string
      queryid:
        type: integer
      total_exec_time:
        type: number
    type: object
  models.ResponseError:
    properties:
      error:
        type: string
    type: object
info:
  contact: {}
  description: This is a api documentation for getting database queries.
  title: Swagger Database Query API
  version: "1.0"
paths:
  /queries:
    get:
      consumes:
      - application/json
      description: API for get  queries
      parameters:
      - default: 10
        in: query
        name: limit
        type: integer
      - default: 1
        in: query
        name: page
        type: integer
      - enum:
        - select
        - insert
        - update
        - delete
        in: query
        name: query_type
        type: string
      - default: asc
        enum:
        - asc
        - desc
        in: query
        name: sort_by_time_spent
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GetQueriesResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseError'
      summary: Get queries
      tags:
      - query
swagger: "2.0"
